source 'https://rubygems.org'

gem 'rails', '4.2.5'
gem 'sqlite3'
gem 'sass-rails'
gem 'uglifier'
gem 'will_paginate'
gem 'bootstrap-will_paginate'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'paperclip'
gem 'simple_form'
gem 'bootstrap-sass'
gem 'devise'
gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
gem 'omniauth-linkedin'
gem 'mail_form'
gem 'acts_as_votable'
gem 'kaminari'
gem 'jquery-turbolinks'

group :development, :test do
  gem 'byebug'
  gem 'web-console'
  gem 'spring'
  gem 'carrierwave'
  gem 'capybara'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end
